# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - takocheung

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Frontend build
        working-directory: frontend
        run: |
          npm install
          npm install @vue/cli-service
          npx -p @vue/cli vue-cli-service build --mode development
          
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: fb
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: fb

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'takocheung'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_637CAD7870BB4B45A4E3177612A3FE35 }}
          package: .
